### ISSUE TITLE
vue的功能build后如何运行

### ISSUE THREAD

**Issue by haitunxiaomo** [marsgis/mars3d-es5-example#1]
vue 代码执行npm run build后，代码也是无法运行的。官网上的是直接npm run serve启动的工程吗

**Comment by muyao1987** [comment]
build后，在dist目录下，http方式访问 dist\index.html 即可
![image](https://user-images.githubusercontent.com/18432449/157185875-7f9f1528-a1a1-4681-90f6-2a463c3c3f8d.png)

**Comment by haitunxiaomo** [comment]
> 执行npm run build后，代码也是无法运行的。官网上的是直接npm run serve启动的工程吗

你这个不是es5版本的处理方法吧，之前你们不是有有vue版本的。vue版本怎么处理的
