### ISSUE TITLE
Import libs without poisoning index.html

### ISSUE THREAD

**Issue by francesco-gallo** [marsgis/mars3d-es5-example#2]
Hello, is there a way to import contextually the libraries? In an angular application using this method all the css (expecially bootstrap and admui) will break any other css using the same generic classes (and in the angular example there is no use of the libs)

Thanks

**Comment by muyao1987** [comment]
This repository example is based on es5 native JS code and can be referenced to other repositories
https://github.com/marsgis/mars3d-angular-template 
https://github.com/marsgis/mars3d-vue-example

**Comment by francesco-gallo** [comment]
I already took a look at the angular template, both it and the "cesium angular template" (https://github.com/Developer-Plexscape/cesium-angular-example) referenced there have no widgets that needed the "public" root folder injection.
