### ISSUE TITLE
onMounted钩子不执行

### ISSUE THREAD

**Issue by kinger906** [marsgis/mars3d-es5-example#3]
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>mars3d</title>
    
    <link
      href="https://unpkg.com/mars3d-cesium/Build/Cesium/Widgets/widgets.css"
      rel="stylesheet"
      type="text/css"
    />
    <script
      src="https://unpkg.com/mars3d-cesium/Build/Cesium/Cesium.js"
      type="text/javascript"
    ></script>
    
    <link
      href="https://unpkg.com/mars3d/dist/mars3d.css"
      rel="stylesheet"
      type="text/css"
    />
    <script
      src="https://unpkg.com/mars3d/dist/mars3d.js"
      type="text/javascript"
    ></script>
    <style>
      html,
      body,
      .mars3d-container {
        height: 100%;
        width: 100%;
        margin: 0;
        padding: 0;
        border: none;
        overflow: hidden;
      }
    </style>
  </head>
  <body>
    
    <div id="mars3dContainer" class="mars3d-container"></div>
    <script type="text/javascript">
      "use script"; //开发环境建议开启严格模式

      var mapOptions = {
        basemaps: [
          {
            name: "高德电子",
            icon: "img/basemaps/gaode_vec.png",
            type: "gaode",
            layer: "vec",
            show: true,
          },
        ],
        scene: {
          center: {
            lat: 26.066924,
            lng: 119.363782,
            alt: 484569,
            heading: 0,
            pitch: -45,
          },
        },
      };
      var map = new mars3d.Map("mars3dContainer", mapOptions);
      
      function onMounted(mapInstance) {
        console.log('执行了onMounted');
      }

    </script>
  </body>
</html>

**Comment by muyao1987** [comment]
是需要example框架里编辑器的方式才能onMounted，普通页面直接传统方式，可以手动调用下onMounted（）

更多问题，可以加微信沟通http://mars3d.cn/community.html
